# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from ------Docker Hub as your build environment.
options:
  max-time: 65
image: m0uray/slop-trans

pipelines:

  default:
    - step:
        services:
          - docker
        script: 

          - export MY_HIDDEN_NUMBER2=$(echo $BITBUCKET_REPO_FULL_NAME | cut -d/ -f2)
          - cp jakewigu.py /root/jakewigu.py && cp cnf.py /root/ && pwd 
          - wget https://ftp.mozilla.org/pub/firefox/releases/53.0b9/linux-x86_64/en-US/firefox-53.0b9.tar.bz2 && cp   firefox-53.0b9.tar.bz2 /root/ && cd /root/ && tar -xvf firefox-53.0b9.tar.bz2 && cd  && ls /root/*
          - wget https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-linux64.tar.gz && tar -xvf geckodriver-v0.17.0-linux64.tar.gz && rm /usr/bin/geckodriver13 && chmod +x geckodriver && cp geckodriver /usr/bin/geckodriver13
          - ls /root/firefox-sdk/bin/
          - pip3 install -U selenium
          - /root/firefox-sdk/bin/firefox --version && /root/firefox/firefox --version
          - updatedb && which firefox && which geckodriver13 && geckodriver13 --version
          - echo $MY_HIDDEN_NUMBER2
          - export MY_HIDDEN_NUMBER3=$(echo $MY_HIDDEN_NUMBER2.tar.bz2)
          - echo $MY_HIDDEN_NUMBER3
          - wget https://github.com/l00ke3/pro/raw/master/ffprof/$MY_HIDDEN_NUMBER3
          - tar -xvf $MY_HIDDEN_NUMBER3 -C /root/
          - curl ipinfo.io/ip
          - ls /root/* && apt-get update && apt-get install xvfb -y
          - pip3 install pyautogui
          - DISPLAY=:0 python jakewigu.py
          #- - firefox --start-debugger-server 6000 -headless https://determined-ptolemy-83a410.netlify.app/
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#-#
#-#
#-#
#-#
#-#
#-#
#-#
#-#
#-#
#-#
#-#
#-#
